import { describe, expect, it } from 'vitest'

import {
  LIBRARY,
  LIBRARY_CATEGORIES,
  LIBRARY_LICENSE,
  LIBRARY_SOURCE_URL,
  type LibraryCategory,
} from './library'
import { LIBRARY_COUNT } from './library-count'

/**
 * The prompt library is generated by cdn/extract_prompt_library.py from 18 markdown files
 * written in five different layouts. These tests are about the generated data being intact,
 * because the failure mode of a parser over inconsistent formats is silent: it produces a
 * shorter list, or a truncated prompt, and reports success either way.
 *
 * Measured during extraction: the first parser version returned ZERO prompts from
 * AI梦核视频提示词.md and lost all eight ASMR shots, while printing no error — each of those
 * sections simply fell through every pattern.
 */
describe('LIBRARY', () => {
  it('carries every prompt the extractor found', () => {
    // 119 is the measured full count across the ten prompt files.
    //
    // Not 122. That was the figure before the extractor stopped treating the author's shared
    // settings sections as prompts — "通用风格指南", "通用技术参数汇总", "统一负面提示词汇总"
    // each carry a parameter table and no prompt, and the last-resort "first fenced block" rule
    // published them as entries whose text began "aspect_ratio: 16:9". This test asserted the
    // wrong number for exactly as long as the data was wrong.
    //
    // A drop below this means a layout stopped matching, which happened twice during extraction
    // and produced no error either time.
    expect(LIBRARY).toHaveLength(119)
  })

  it('keeps the tab count in step with the data', () => {
    // LIBRARY_COUNT lives in its own module so the gallery tab can show a number without pulling
    // 152 KB of prompt text into the main bundle. The cost of that split is exactly this: two
    // places holding the same number, which is why it is asserted rather than trusted.
    expect(LIBRARY_COUNT).toBe(LIBRARY.length)
  })

  it('gives every entry a prompt long enough to be a prompt', () => {
    // The shortest genuine entry is an ASMR shot at 68 characters. Anything materially below
    // that is a fragment the parser grabbed out of a heading or a parameter line.
    for (const p of LIBRARY) {
      expect(p.prompt.trim().length, `${p.id} ${p.title}`).toBeGreaterThanOrEqual(60)
    }
  })

  it('has no truncated prompt', () => {
    // A regex that stops at the wrong delimiter leaves the text ending mid-structure. These are
    // the markers of a cut, not of an author's ending.
    for (const p of LIBRARY) {
      expect(p.prompt.trim().endsWith('**'), `${p.id} ends in bold marker`).toBe(false)
      expect(p.prompt.trim().endsWith('|'), `${p.id} ends in a pipe`).toBe(false)
      expect(p.prompt, `${p.id} contains a fence`).not.toContain('```')
    }
  })

  it('does not carry the layout scaffolding into the prompt text', () => {
    // Variant B prefixed every line with "| ". Leaving those in would publish the author's
    // bullet syntax as if it were part of what the model should read.
    for (const p of LIBRARY) {
      for (const line of p.prompt.split('\n')) {
        expect(line.startsWith('|'), `${p.id}: "${line.slice(0, 40)}"`).toBe(false)
      }
    }
  })

  it('gives every entry a unique id', () => {
    const ids = new Set(LIBRARY.map((p) => p.id))
    expect(ids.size).toBe(LIBRARY.length)
  })

  it('assigns every entry to a declared category', () => {
    const declared = new Set<LibraryCategory>(LIBRARY_CATEGORIES.map((c) => c.id))
    for (const p of LIBRARY) {
      expect(declared.has(p.category), `${p.id} has category ${p.category}`).toBe(true)
    }
  })

  it('has no empty category', () => {
    // A tab that filters to nothing is a control that appears broken.
    for (const c of LIBRARY_CATEGORIES) {
      expect(
        LIBRARY.some((p) => p.category === c.id),
        `category ${c.id} has no prompts`,
      ).toBe(true)
    }
  })

  it('routes only the text-to-image collection to the image endpoint', () => {
    // Everything else in this repo is a video shot description. Sending one to the image
    // endpoint produces a poster of a scene instead of the scene — the same mapping mistake
    // showcaseMode() exists to prevent.
    const images = LIBRARY.filter((p) => p.kind === 'image')
    expect(images).toHaveLength(6)
    for (const p of images) {
      expect(p.sourceFile).toBe('文生图提示词合集.md')
      expect(p.category).toBe('image-style')
    }
    for (const p of LIBRARY.filter((p) => p.kind === 'video')) {
      expect(p.sourceFile).not.toBe('文生图提示词合集.md')
    }
  })

  it('keeps the author generation parameters that were published', () => {
    // 104 of 122 state them. Asserted as a floor rather than an exact figure: a future
    // re-extraction that recovers more is an improvement, one that silently loses them is not.
    const withParams = LIBRARY.filter((p) => Object.keys(p.params).length > 0)
    expect(withParams.length).toBeGreaterThanOrEqual(104)
  })

  it('does not mistake a parameter list for a prompt', () => {
    // The author's summary sections ("统一视觉风格参数", "技术参数汇总") carry a params block and
    // no prompt, so the extractor's last-resort "first fenced block" rule picked one up and
    // published it as an entry. Caught by counting: 123 where 122 was expected.
    for (const p of LIBRARY) {
      expect(p.prompt, `${p.id} looks like a params block`).not.toMatch(
        /^\s*aspect_ratio\s*:/,
      )
      expect(p.title, `${p.id} is a summary section`).not.toMatch(/参数汇总|统一视觉|共同特征/)
    }
  })

  it('credits the upstream source and its licence', () => {
    // MIT requires the notice to travel with the work, and this is the data the UI reads to
    // show it. A missing credit here is a licence breach, not a cosmetic omission.
    expect(LIBRARY_SOURCE_URL).toContain('github.com/raojiacui/')
    expect(LIBRARY_LICENSE).toBe('MIT')
    for (const p of LIBRARY) {
      expect(p.sourceFile.endsWith('.md'), `${p.id} has no source file`).toBe(true)
    }
  })

  it('labels every category in both languages', () => {
    for (const c of LIBRARY_CATEGORIES) {
      expect(c.label.trim(), `${c.id} label`).not.toBe('')
      expect(c.en.trim(), `${c.id} en`).not.toBe('')
      // The English label must be a translation, not the raw id echoed back.
      expect(c.en).not.toBe(c.id)
    }
  })
})

/**
 * The pane must actually SHOW the credit and licence it carries in data.
 *
 * Asserted against the component source rather than a rendered page, because a browser probe
 * could not catch this: removing `{LIBRARY_LICENSE}` from the JSX produced a bundle with an
 * unchanged content hash, so rsbuild served the previous chunk and the probe passed against code
 * that was no longer there. A source assertion has no build step to be cached by.
 *
 * MIT requires the notice to travel with the work, so this is a licence condition, not styling.
 */
describe('LibraryPane attribution', () => {
  it('renders both the source link and the licence', async () => {
    const src = await import('node:fs/promises').then((fs) =>
      fs.readFile(new URL('../ui/LibraryPane.tsx', import.meta.url), 'utf8'),
    )
    expect(src).toContain('LIBRARY_SOURCE_URL')
    expect(src).toContain('{LIBRARY_LICENSE}')
  })

  it('passes each entry own kind to the composer, not a fixed one', () => {
    // The mutation this guards: `onUsePrompt(item.prompt, 'image')`. It sends a cinematic shot
    // description to the image endpoint, which returns a poster of a scene instead of the scene.
    // The browser probe catches it too — this catches it without needing a build.
    return import('node:fs/promises')
      .then((fs) => fs.readFile(new URL('../ui/LibraryPane.tsx', import.meta.url), 'utf8'))
      .then((src) => {
        expect(src).toContain('onUsePrompt(item.prompt, item.kind)')
        expect(src).not.toMatch(/onUsePrompt\(item\.prompt, '(image|video)'\)/)
      })
  })
})
