"""Parse the awesome-seedance-2-prompts README into structured rows.

Why parse the README rather than call their API: the prompts live in a Payload CMS behind
`CMS_API_KEY`, which we do not have and should not want. The README is the published artifact —
CC BY 4.0, regenerated by their own workflow — and it carries everything an entry needs: title,
full prompt text, author with profile link, source post, publish date, a thumbnail, and for most
entries an MP4 on GitHub Releases.

Their statistics table says 6,156 prompts. That is the CMS total, NOT what the README contains;
the file holds ~106. Worth stating because "collect all of them" is not achievable from a public
source, and quietly shipping 106 while implying 6,156 would be the kind of gap nobody notices
until they count.
"""

import json
import re
import sys
import urllib.parse
import urllib.request
from pathlib import Path

sys.stdout.reconfigure(encoding="utf-8", errors="replace")

RAW = "https://raw.githubusercontent.com/YouMind-OpenLab/awesome-seedance-2-prompts/main/README.md"
OUT = Path(__file__).parent / "_seedance_rows.json"


def fetch() -> str:
    req = urllib.request.Request(RAW, headers={"User-Agent": "Mozilla/5.0"})
    return urllib.request.urlopen(req, timeout=180).read().decode("utf-8")


def main() -> int:
    md = fetch()
    print(f"README: {len(md)} bytes, {md.count(chr(10))} lines")

    # Entries are `### <n>. <title>` or `### <title>`. Split on the heading so each chunk holds
    # exactly one entry's body — a regex trying to match a whole entry in one pattern breaks on
    # the first entry whose fields appear in a different order, and they do vary between the
    # featured block and the main list.
    parts = re.split(r"\n### ", md)
    print(f"chunks after split: {len(parts)}")

    rows = []
    for chunk in parts[1:]:
        head, _, body = chunk.partition("\n")
        title = head.strip()
        # Featured headings carry a leading sequence number that is not part of the title.
        title = re.sub(r"^\d+\.\s*", "", title).strip()
        # Strip trailing badges/anchors some headings carry.
        title = re.sub(r"\s*<[^>]+>\s*$", "", title).strip()
        if not title or title.lower().startswith(("contributing", "license", "acknowled")):
            continue

        # The prompt is the first fenced block. Language hint on the fence is inconsistent, so it
        # is not relied on.
        fence = re.search(r"```[a-zA-Z]*\n(.*?)\n```", body, re.S)
        if not fence:
            continue
        prompt = fence.group(1).strip()
        if len(prompt) < 40:
            # Short fences in this file are `[Style]`-style fragments quoted in prose, not prompts.
            continue

        # id, from the Watch Video link or the release asset. Needed for the video URL and as a
        # stable key — titles repeat in this file.
        pid = None
        m = re.search(r"seedance-2-0-prompts\?id=(\d+)", body)
        if m:
            pid = int(m.group(1))
        if pid is None:
            m = re.search(r"releases/download/videos/(\d+)\.mp4", body)
            if m:
                pid = int(m.group(1))

        # Thumbnails are raw HTML `<img src>`, NOT markdown images. The only markdown images in an
        # entry are the shields.io language/featured badges, so a markdown-image pattern finds
        # nothing but badges — which is why the first version of this reported 0 thumbnails on 105
        # entries that all have one.
        thumb = None
        for m in re.finditer(r"""<img[^>]+src=["']([^"']+)["']""", body):
            u = m.group(1)
            if "shields.io" in u or "/badge" in u:
                continue
            thumb = u
            break

        video = None
        m = re.search(r"(https://github\.com/[^\s)\"']+/releases/download/videos/\d+\.mp4)", body)
        if m:
            video = m.group(1)

        # Attribution is required by CC BY, so these are extracted, not optional.
        author = None
        author_link = None
        m = re.search(r"\[([^\]]+)\]\((https?://(?:x|twitter)\.com/[^)\s]+)\)", body)
        if m:
            author, author_link = m.group(1).strip(), m.group(2)

        source = None
        m = re.search(r"(https://(?:x|twitter)\.com/[^\s)]*/status/\d+)", body)
        if m:
            source = m.group(1)

        published = None
        m = re.search(r"(\d{4}-\d{2}-\d{2})", body)
        if m:
            published = m.group(1)

        # The badge records the language the prompt was WRITTEN in; the prompt text in this file is
        # the English translation. So the badge is read rather than the text sniffed — sniffing
        # reports every entry as English, which is true of the text and false of the entry.
        badge = re.search(r"badge/lang-([^-]+)-", body)
        lang = "en"
        if badge:
            raw_lang = urllib.parse.unquote(badge.group(1))
            lang = "zh" if re.search(r"[一-鿿]", raw_lang) else "en"

        rows.append(
            {
                "id": pid,
                "title": title,
                "prompt": prompt,
                "thumbnail": thumb,
                "video": video,
                "author": author,
                "authorLink": author_link,
                "source": source,
                "published": published,
                "lang": lang,
                "chars": len(prompt),
            }
        )

    # Deduplicate on id, keeping the first (the featured block appears before the main list, and
    # its entries carry the richer metadata).
    seen = set()
    unique = []
    for r in rows:
        key = r["id"] if r["id"] is not None else r["title"]
        if key in seen:
            continue
        seen.add(key)
        unique.append(r)

    print(f"\nparsed {len(rows)} entries, {len(unique)} unique")
    print(f"  with id        {sum(1 for r in unique if r['id'])}")
    print(f"  with thumbnail {sum(1 for r in unique if r['thumbnail'])}")
    print(f"  with video     {sum(1 for r in unique if r['video'])}")
    print(f"  with author    {sum(1 for r in unique if r['author'])}")
    print(f"  with source    {sum(1 for r in unique if r['source'])}")
    print(f"  chinese        {sum(1 for r in unique if r['lang'] == 'zh')}")
    print(f"  prompt chars   min {min(r['chars'] for r in unique)} max {max(r['chars'] for r in unique)}")

    OUT.write_text(json.dumps(unique, ensure_ascii=False, indent=1), encoding="utf-8")
    print(f"\nwrote {OUT}")

    print("\nfirst three:")
    for r in unique[:3]:
        print(f"  [{r['id']}] {r['title'][:60]}")
        print(f"      author={r['author']} thumb={(r['thumbnail'] or '')[:60]}")
        print(f"      video={(r['video'] or '-')[:70]}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
